export const alldogitem = [
    {name: "Farmina Dry Food - Matisse Kitten",price: "347", review: "5.0" , description :"The Matisse Premium Dry Cat Food is a complete food for cats and it features chicken & rice as their main ingredients. Rich in taurine (an essential nutrient for cats) and is highly digestible. Taurine, not produced naturally by Cat’s body, is needed for the prevention of the buildup of plaque in the arteries throughout the body.",available: true, discount: "10%",cutprice: "385"},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
    {name: "",price: "", review: "" , description :"",available: true, discount: "",cutprice: ""},
]
